openapi: 3.0.0
info:
  title: Bookstore API - Orders
  version: 1.0.0
  description: APIs for managing orders in the bookstore.
servers:
  - url: http://localhost:5000
paths:
  /api/v1/orders:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewOrder"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    get:
      summary: Get all orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
  /api/v1/orders/{orderId}/cancel:
    put:
      summary: Cancel an existing order
      parameters:
        - in: path
          name: orderId
          required: true
          description: The ID of the order to cancel
          schema:
            type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
  /api/v1/orders/customer/{customerId}:
    get:
      summary: Get orders by customer ID
      parameters:
        - in: path
          name: customerId
          required: true
          description: The ID of the customer
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: The order ID.
        customerId:
          type: integer
          description: The ID of the customer who placed the order.
        totalAmount:
          type: number
          description: The total amount of the order.
        status:
          type: string
          description: The status of the order.
    NewOrder:
      type: object
      properties:
        customerId:
          type: integer
          description: The ID of the customer placing the order.
        bookIds:
          type: array
          description: An array of book IDs included in the order.
          items:
            type: integer
        quantities:
          type: array
          description: An array of quantities corresponding to the books in the order.
          items:
            type: integer
